PutTheMoneyToTheSock/config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'
  
  scope "(:locale)", locale: /en|ro/ do
    root to: 'welcome#index'
  end
  
  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :targets, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

end

PutTheMoneyToTheSock/app/models/tag.rb
class Tag < ApplicationRecord

    validates :title, presence: true, length: { minimum: 1, maximum: 500}

    belongs_to :user
    has_and_belongs_to_many :expenses
end

PutTheMoneyToTheSock/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index

    if current_user
      @tags = Tag.where(user_id: current_user.id)
    end
  end

  def edit

    @button_text = "Update"
    @tag = Tag.find(params[:id])

  end

  def update

    @tag = Tag.find(params[:id])

    if @tag.update_attributes(tag_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end

  def new

    @button_text = "Create"
    @tag = Tag.new

  end

  def create

    @tag = Tag.new(tag_params)

    if current_user
      @tag.user_id = current_user.id
    else
      render 'new'
    end

    if @tag.save
      redirect_to action: 'index'
    else
      render 'new'
    end

  end

  def destroy

    @tag = Tag.find(params[:id])
    @tag.destroy

    flash[:success] = "Tag deleted!"
  
    redirect_to tags_path

  end

  private

    def tag_params
      params.require(:tag).permit(:title, :description, :ammount,
                                      :tag_date, :currency)
    end
end

PutTheMoneyToTheSock/app/helpers/tags_helper.rb
module TagsHelper
end

PutTheMoneyToTheSock/app/views/tags/_error_messages.html.erb
<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@tag.errors.count, "error") %>.
    </div>
    <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

PutTheMoneyToTheSock/app/views/tags/_form.html.erb
<%= form_for(@tag, class: "justify-content-center") do |f| %>
    <%= render 'error_messages', object: @tag %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <%= f.submit @button_text, class: "btn btn-primary" %>
<% end %>

PutTheMoneyToTheSock/app/views/tags/edit.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Edit Tag</h2>
</div>

</br>
</br>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <%= render 'form' %>
        </div>
    </div>
</div>

</br>
</br>

PutTheMoneyToTheSock/app/views/tags/index.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Your Tags</h2>
</div>


<div class="table-container">
    </br>

    <div class="text-center">
      <%= link_to new_tag_path(@tag), class: "btn btn-sm btn-info" do%>
        <i class="fas fa-plus-circle"></i> Add New Tag
      <% end %>
    </div>

    <table id="tags_table" class="container">
      <thead>
        <tr>
          <th><h1>Tag Title</h1></th>
          <th><h1>Actions</h1></th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
          <tr>
            <td><%= tag.title %></td>
            <td>

              <%= link_to edit_tag_path(tag), class: "btn btn-sm btn-info" do%>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
              
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>


<script type="text/javascript">

  $(document).ready(function() {
    $('#tags_table').DataTable();
  });

</script>

<style>
@charset "UTF-8";
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);

.table-container {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  line-height: 1.42em;
  color:#A7A1AE;
  background-color:#1F2739;
  padding-bottom: 30px;
}

.table-container h1 {
  font-size:3em; 
  font-weight: 300;
  line-height:1em;
  text-align: center;
  color: #4DC3FA;
}

.table-container h2 {
  font-size:1em; 
  font-weight: 300;
  text-align: center;
  display: block;
  line-height:1em;
  padding-bottom: 2em;
  color: #FB667A;
}

.table-container h2 a {
  font-weight: 700;
  text-transform: uppercase;
  color: #FB667A;
  text-decoration: none;
}

.table-container .blue { color: #185875; }
.table-container .yellow { color: #FFF842; }

.table-container .container th h1 {
	  font-weight: bold;
	  font-size: 1em;
  text-align: left;
  color: #185875;
}

.table-container .container td {
	  font-weight: normal;
	  font-size: 1em;
  -webkit-box-shadow: 0 2px 2px -2px #0E1119;
	   -moz-box-shadow: 0 2px 2px -2px #0E1119;
	        box-shadow: 0 2px 2px -2px #0E1119;
}

.table-container .container {
	  text-align: left;
	  overflow: hidden;
	  width: 80%;
	  margin: 0 auto;
  display: table;
  padding: 0 0 8em 0;
}

.table-container .container td, .container th {
	  padding-bottom: 2%;
	  padding-top: 2%;
  padding-left:2%;  
}

/* Background-color of the odd rows */
.table-container .container tr:nth-child(odd) {
	  background-color: #323C50;
}

/* Background-color of the even rows */
.table-container .container tr:nth-child(even) {
	  background-color: #2C3446;
}

.table-container .container th {
	  background-color: #1F2739;
}

.table-container .container td:first-child { color: #FB667A; }

.table-container .container tr:hover {
   background-color: #464A52;
  -webkit-box-shadow: 0 6px 6px -6px #0E1119;
	   -moz-box-shadow: 0 6px 6px -6px #0E1119;
	        box-shadow: 0 6px 6px -6px #0E1119;
}

.table-container .container td:hover {
  background-color: #FFF842;
  color: #403E10;
  font-weight: bold;
  
  box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
  transform: translate3d(6px, -6px, 0);
  
  transition-delay: 0s;
	  transition-duration: 0.4s;
	  transition-property: all;
  transition-timing-function: line;
}

.jumbotron {
  margin-bottom: 0 !important;
}
</style>

PutTheMoneyToTheSock/app/views/tags/new.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Add New Tag</h2>
</div>

</br>
</br>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <%= render 'form' %>
        </div>
    </div>
</div>

</br>
</br>