PutTheMoneyToTheSock/config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'
  
  scope "(:locale)", locale: /en|ro/ do
    root to: 'welcome#index'
  end
  
  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :targets, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

end

PutTheMoneyToTheSock/app/views/layouts/_features.html.erb
<div class="features-boxed">
    <div class="container">
        <div class="intro">
            <h2 class="text-center"><%= t('home.features') %></h2>
        </div>
        <div class="row justify-content-centerfeatures">
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-tablet-alt icon"></i> <i class="fa fa-mobile-alt icon"></i> <i class="fa fa-desktop icon"></i>
                    <h3 class="name"><%= t('home.works_on_everything') %></h3>
                    <p class="description"><%= t('home.works_on_everything_text') %></p></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-clock icon"></i>
                    <h3 class="name"><%= t('home.always_available') %></h3>
                    <p class="description"><%= t('home.always_available_text') %></p></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-globe icon"></i>
                    <h3 class="name"><%= t('home.international') %></h3>
                    <p class="description"><%= t('home.international_text') %></p></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-list-alt icon"></i>
                    <h3 class="name"><%= t('home.customizable') %></h3>
                    <p class="description"><%= t('home.customizable_text') %></p></div>
            </div>
        </div>
    </div>
</div>

PutTheMoneyToTheSock/app/views/layouts/_footer.html.erb
<div class="footer-dark" id="footer">
    <div class="container">
        <div id="footer">
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-md-3 item">
                        </div>
                        <div class="col-sm-6 col-md-3 item">
                        </div>
                        <div class="col-md-6 item text">
                            <h3>
                                <%= t('home.subscribe_to_newsletter') %>
                            </h3>
                            <form class="form-inline" method="post">
                                <div class="form-group"><input class="form-control" type="email" name="email"
                                        placeholder="Your Email" /></div>
                                <div class="form-group"><button class="btn btn-primary" type="submit">
                                        <%= t('home.subscribe') %></button></div>
                            </form>
                        </div>
                    </div>
                    <p class="copyright">Put The Money To The Sock © 2019</p>
                </div>
            </footer>
        </div>
    </div>
</div>

PutTheMoneyToTheSock/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>  

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><i class="fas fa-money-bill-alt navbar-icon gradient-icon"></i><i class="fa fa-arrow-right navbar-icon gradient-icon"></i><i class="fa fa-socks navbar-icon gradient-icon"></i></li>
        <li><p>&nbsp;&nbsp;</p></li>
        <li>&nbsp;&nbsp;<%= link_to "PutTheMoneyToTheSock", root_path, class: "navbar-brand" %></li>
      </ul>

      <% if user_signed_in? %>
        
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to("Expenses", expenses_path, class: "navbar-brand") %>
          </li>
          <li>
            <%= link_to("Reports", reports_path, class: "navbar-brand") %>
          </li>
          <li>
            <%= link_to("Targets", targets_path, class: "navbar-brand") %>
          </li>
          <li>
            <%= link_to("Tags", tags_path, class: "navbar-brand") %>
          </li>
          <li>
            <%= link_to('<i class="fas fa-sign-out-alt"></i> Sign Out'.html_safe, destroy_user_session_path, method: :delete, class: "navbar-brand navbar-right") %>        
          </li>
        </ul>

      <% else %>
      
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><%= t('home.log_in')%></b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu">
              <li>
                <div class="row">
                  <div class="col-md-12">
                    <%= t('home.sign_in_with') %>
                    <div class="social-buttons">
                      <%= link_to omniauth_authorize_path(:user, :facebook), class: "btn btn-fb" do %>
                        <i class="fab fa-facebook"></i> Facebook
                      <% end %>
                      <%= link_to omniauth_authorize_path(:user, :twitter), class: "btn btn-fb" do %>
                        <i class="fab fa-twitter"></i> Twitter
                      <% end %>
                    </div>
                    <%= t('general.or') %>

                    <%= simple_form_for(:user, :url => session_path(:user), class: "form") do |f| %>
                      <%= f.error_notification %>

                      <div class="form-group">
                        <label class="sr-only" for="email">Email</label>
                        <%= f.input_field :email,
                                          required: false,
                                          autofocus: true,
                                          input_html: { autocomplete: "email" },
                                          class: "form-control field-with-errors",
                                          label: false %>
                      </div>
                      <div class="form-group">
                        <label class="sr-only" for="password"><%= t('home.password') %></label>
                        <%= f.input_field :password,
                                          required: false,
                                          input_html: { autocomplete: "current-password" },
                                          class: "form-control field-with-errors",
                                          label: false %>
                        <div class="help-block text-right">
                          <%= link_to t(".forgot_your_password"), new_password_path(:user) %><br />
                        </div>
                      </div>
                      <div class="form-group">
                        <%= f.button :submit, t("home.log_in"), class: "btn btn-primary btn-block" %>
                      </div>
                      <div class="checkbox">
                        <label>
                          <%= f.input_field :remember_me,
                                            label: false,
                                            as: :boolean %>
                          <%= t('home.remember_me') %>
                        </label>
                      </div>
                    <% end %>

                  </div>
                  <div class="bottom text-center">
                    <%= t('home.new_here') %>
                    <%= link_to t('home.join'), controller: "devise/registrations", action: "new" %>
                  </div>

                </div>
              </li>
            </ul>
          </li>
        </ul>

      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

PutTheMoneyToTheSock/app/views/layouts/_welcome.html.erb
<link rel="stylesheet" href="https://cdn.lineicons.com/1.0.0/LineIcons.min.css">
<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css" />

<div class="container-fluid bg">
    <div class="container custom-container-welcome">
        <div class="row">
            <div class="col-md-8 ">
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-lg-2">
                        <i class="lni lni-enter" aria-hidden="true"></i>
                    </div>

                    <div class="col-sm-9 col-md-10 col-lg-10">
                        <h1 class="heading"><%= t('home.register') %></h1>
                    </div>
                </div>

                </br>
                </br>

                <div class="row">
                    <div class="col-sm-3 col-md-2 col-lg-2">
                        <i class="lni lni-user" aria-hidden="true"></i>
                    </div>

                    <div class="col-sm-9 col-md-10 col-lg-10">
                        <h1 class="heading"><%= t('home.create_your_profile') %></h1>
                    </div>
                </div>

                </br>
                </br>

                <div class="row">
                    <div class="col-sm-3 col-md-2 col-lg-2">
                        <i class="lni lni-cloud-upload" aria-hidden="true"></i>
                    </div>

                    <div class="col-sm-9 col-md-10 col-lg-10">
                        <h1 class="heading"><%= t('home.upload_expenses') %></h1>
                    </div>
                </div>

                </br>
                </br>

                <div class="row">
                    <div class="col-sm-3 col-md-2 col-lg-2">
                        <i class="lni lni-search" aria-hidden="true"></i>
                    </div>

                    <div class="col-sm-9 col-md-10 col-lg-10">
                        <h1 class="heading"><%= t('home.manage_your_money') %></h1>
                    </div>
                </div>

                </br>
                </br>
                </br>
                </br>
            </div>

            <div class="col-md-4 custom-card-welcome">
                <div class="card regform wow bounce animated" data-wow-delay="0.05s">
                    <div class="card-body regform">
                        <div class="myform form ">
                            <div class="logo mb-3">
                                <div class="col-md-12 text-center">
                                    <h1 class="sign"><%= t('home.join') %></h1>
                                </div>
                            </div>

                            <%= simple_form_for(:user, :url => registration_path(:user), :html => { :class => 'custom-form-welcome'}) do |f| %>
                                <%= f.error_notification %>
                                <div class="form-group">
                                    <label for="email"><%= t('home.email_address') %></label>
                                    <%= f.input_field :email,
                                                        required: true,
                                                        autofocus: true,
                                                        input_html: { autocomplete: "email" },
                                                        class: "form-control field-with-errors",
                                                        label: false %>
                                </div>
                                <div class="form-group">
                                    <label for="password"><%= t('home.password') %></label>
                                    <%= f.input_field :password,
                                                        required: true,
                                                        hint: (t('devise.shared.minimum_password_length', count: @minimum_password_length) if @minimum_password_length),
                                                        input_html: { autocomplete: "new-password" },
                                                        class: "form-control field-with-errors",
                                                        label: false %>
                                </div>
                                <div class="form-group">
                                    <label for="email"><%= t('home.password_confirmation') %></label>
                                    <%= f.input_field :password_confirmation,
                                                        required: true,
                                                        input_html: { autocomplete: "new-password" },
                                                        class: "form-control field-with-errors",
                                                        label: false %>
                                </div> 
                                <div class="col-md-12 text-center mb-3">
                                    <div class="form-group">
                                        <%= f.button :submit, t('home.sign_up'), class: "btn btn-block mybtn btn-primary tx-tfm" %>
                                    </div>
                                </div>
                            <% end %>

                            <div class="col-md-12 ">
                                <div class="form-group">
                                    <p class="text-center">
                                        <%= link_to t('home.already_have_an_account'), controller: "devise/sessions", action: "new" %>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $("#signup").click(function () {
        $("#first").fadeOut("fast", function () {
            $("#second").fadeIn("fast");
        });
    });

    $("#signin").click(function () {
        $("#second").fadeOut("fast", function () {
            $("#first").fadeIn("fast");
        });
    });

</script>

PutTheMoneyToTheSock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PutTheMoneyToTheSock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_include_tag "https://code.highcharts.com/highcharts.src.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', :media => "all", 'data-turbolinks-track': 'reload' %>
    
    <%= favicon_link_tag asset_path('favicon-96x96.png') %>
  </head>

  <body>
    <div class="body" id="wrapper">

      <div id="header">
      <%= render 'layouts/header' %>
      </div>


      <div id="content">
        <% flash.each do |name, msg| -%>
          <%= content_tag(:div,  class: "alert fade in alert-#{name}") do %>
            <%= msg %>
            <button class="close" data-dismiss="alert">×</button>
          <% end %>
        <% end -%>
        <%= yield %>
      </div>
      
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>