PutTheMoneyToTheSock/config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  root to: 'home#index'
  
  scope "(:locale)", locale: /en|ro/ do
    root to: 'welcome#index'
  end
  
  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :targets, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

end

PutTheMoneyToTheSock/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable,
         :omniauthable, omniauth_providers: [:facebook, :twitter]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  has_many :expenses
  has_many :reports
  has_many :targets
  has_many :tags

end

PutTheMoneyToTheSock/app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index

    if current_user
      @expenses = Expense.where(user_id: current_user.id)
    end
  end
    
  def show

    @expense = Expense.includes(:tags).find(params[:id])

  end

  def edit

    @button_text = "Update"
    @expense = Expense.find(params[:id])

    @tags = {}
    Tag.all.collect {|t| @tags[t.title] = t.id }

  end

  def update

    @expense = Expense.find(params[:id])

    handle_tags_for_expense

    if @expense.update_attributes(expense_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end

  def new

    @button_text = "Create"
    @expense = Expense.new

    @tags = {}
    Tag.all.collect {|t| @tags[t.title] = t.id }

  end

  def create

    @expense = Expense.new(expense_params)

    if current_user
      @expense.user_id = current_user.id
    else
      render 'new'
    end

    handle_tags_for_expense

    if @expense.save
      redirect_to action: 'index'
    else
      render 'new'
    end

  end

  def destroy

    @expense = Expense.find(params[:id])
    @expense.destroy

    flash[:success] = "Expense deleted!"
  
    redirect_to expenses_path

  end

  private

    def expense_params
      params.require(:expense).permit(:title, :description, :ammount,
                                      :expense_date, :currency)
    end

    def handle_tags_for_expense
      if params['tag_ids']
        @expense.tags.clear
        tags = params['tag_ids'].map { |id| Tag.find(id) }
        @expense.tags << tags 
    end 

  end

end

PutTheMoneyToTheSock/app/helpers/expenses_helper.rb
module ExpensesHelper
end

PutTheMoneyToTheSock/app/views/expenses/_error_messages.html.erb
<% if @expense.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@expense.errors.count, "error") %>.
    </div>
    <ul>
    <% @expense.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

PutTheMoneyToTheSock/app/views/expenses/_form.html.erb
<%= form_for(@expense, class: "justify-content-center") do |f| %>
    <%= render 'error_messages', object: @expense %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :ammount %>
        <%= f.number_field :ammount, class: 'form-control', step: :any %>
    </div>

    <div class="form-group">
        <%= f.label :currency %>
        <%= f.collection_select :currency, Expense.currencies.to_a.map { |w| [w[0], w[0].humanize.upcase] }, :first, :second, {}, { :class => 'form-control', "data-style" => "btn-primary"} %>
    </div>

    <div class="form-group">
        <%= f.label :expense_date %>
        <%= f.date_field :expense_date, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>


    <div class="form-group">
        <labeL>Tags</label>
       
        <%= select_tag("tag_ids[]", 
                        options_for_select(Tag.all.collect { |tag| [tag.title, tag.id] },
                        @expense.tags.collect { |tag| tag.id}),
                        {:multiple => true, :size => 6, :class => "form-control"})%>
    </div>
    

    <%= f.submit @button_text, class: "btn btn-primary" %>
<% end %>

PutTheMoneyToTheSock/app/views/expenses/edit.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Edit Expense</h2>
</div>

</br>
</br>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <%= render 'form' %>
        </div>
    </div>
</div>

</br>
</br>

PutTheMoneyToTheSock/app/views/expenses/index.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Your Expenses</h2>
</div>


<div class="table-container">
    </br>

    <div class="text-center">
      <%= link_to new_expense_path(@expense), class: "btn btn-sm btn-info" do%>
        <i class="fas fa-plus-circle"></i> Add New Expense
      <% end %>
    </div>

    <table id="expenses_table" class="container">
      <thead>
        <tr>
          <th><h1>Expense Title</h1></th>
          <th><h1>Ammount</h1></th>
          <th><h1>Date</h1></th>
          <th><h1>Description</h1></th>
          <th><h1>Actions</h1></th>
        </tr>
      </thead>
      <tbody>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= link_to expense.title, expense_path(expense) %></td>
            <td><%= expense.ammount.to_s + ' ' + expense.currency.to_s.humanize.upcase %></td>
            <td><%= expense.expense_date %></td>
            <td><%= expense.description %></td>
            <td>

              <%= link_to edit_expense_path(expense), class: "btn btn-sm btn-info" do%>
                <i class="fas fa-edit"></i>
              <% end %>

              <%= link_to expense_path(expense), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
              
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>


<script type="text/javascript">

  $(document).ready(function() {
    $('#expenses_table').DataTable();
  });

</script>

<style>
@charset "UTF-8";
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);

.table-container {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  line-height: 1.42em;
  color:#A7A1AE;
  background-color:#1F2739;
  padding-bottom: 30px;
}

.table-container h1 {
  font-size:3em; 
  font-weight: 300;
  line-height:1em;
  text-align: center;
  color: #4DC3FA;
}

.table-container h2 {
  font-size:1em; 
  font-weight: 300;
  text-align: center;
  display: block;
  line-height:1em;
  padding-bottom: 2em;
  color: #FB667A;
}

.table-container h2 a {
  font-weight: 700;
  text-transform: uppercase;
  color: #FB667A;
  text-decoration: none;
}

.table-container .blue { color: #185875; }
.table-container .yellow { color: #FFF842; }

.table-container .container th h1 {
	  font-weight: bold;
	  font-size: 1em;
  text-align: left;
  color: #185875;
}

.table-container .container td {
	  font-weight: normal;
	  font-size: 1em;
  -webkit-box-shadow: 0 2px 2px -2px #0E1119;
	   -moz-box-shadow: 0 2px 2px -2px #0E1119;
	        box-shadow: 0 2px 2px -2px #0E1119;
}

.table-container .container {
	  text-align: left;
	  overflow: hidden;
	  width: 80%;
	  margin: 0 auto;
  display: table;
  padding: 0 0 8em 0;
}

.table-container .container td, .container th {
	  padding-bottom: 2%;
	  padding-top: 2%;
  padding-left:2%;  
}

/* Background-color of the odd rows */
.table-container .container tr:nth-child(odd) {
	  background-color: #323C50;
}

/* Background-color of the even rows */
.table-container .container tr:nth-child(even) {
	  background-color: #2C3446;
}

.table-container .container th {
	  background-color: #1F2739;
}

.table-container .container td:first-child { color: #FB667A; }

.table-container .container tr:hover {
   background-color: #464A52;
  -webkit-box-shadow: 0 6px 6px -6px #0E1119;
	   -moz-box-shadow: 0 6px 6px -6px #0E1119;
	        box-shadow: 0 6px 6px -6px #0E1119;
}

.table-container .container td:hover {
  background-color: #FFF842;
  color: #403E10;
  font-weight: bold;
  
  box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
  transform: translate3d(6px, -6px, 0);
  
  transition-delay: 0s;
	  transition-duration: 0.4s;
	  transition-property: all;
  transition-timing-function: line;
}

@media (max-width: 800px) {
.table-container .container td:nth-child(4),
.table-container .container th:nth-child(4) { display: none; }
}

.jumbotron {
  margin-bottom: 0 !important;
}
</style>

PutTheMoneyToTheSock/app/views/expenses/new.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Add New Expense</h2>
</div>

</br>
</br>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <%= render 'form' %>
        </div>
    </div>
</div>

</br>
</br>

PutTheMoneyToTheSock/app/views/expenses/show.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">View Expense</h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">


      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @expense.title %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class=" col-md-12 col-lg-12 ">
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <td>Ammount:</td>
                    <td><%= @expense.ammount.to_s + ' ' + @expense.currency.to_s.humanize.upcase %></td>
                  </tr>
                  <tr>
                    <td>Expense date:</td>
                    <td><%= @expense.expense_date %></td>
                  </tr>
                  <tr>
                    <td>Description:</td>
                    <td><%= @expense.description %></td>
                  </tr>
                  <tr>
                    <td>Tags:</td>
                    <td>
                        <% @expense.tags.each do |tag| %>
                          <span class="badge badge-pill badge-primary"><%= tag.title %></span>
                        <% end %>

                    </td>
                  </tr>

                </tbody>
              </table>

              <%= link_to "Back to My Expenses", action: "index", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        <div class="panel-footer">
            <%= link_to edit_expense_path(@expense), class: "btn btn-sm btn-info" do%>
              <i class="fas fa-edit"></i>
            <% end %>
          <span class="pull-right">
            <%= link_to expense_path(@expense), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do %>
                  <i class="fas fa-trash-alt"></i>
            <% end %>
          </span>
        </div>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

<style>

  .user-row {
      margin-bottom: 14px;
  }

  .user-row:last-child {
      margin-bottom: 0;
  }

  .dropdown-user {
      margin: 13px 0;
      padding: 5px;
      height: 100%;
  }

  .dropdown-user:hover {
      cursor: pointer;
  }

  .table-user-information > tbody > tr {
      border-top: 1px solid rgb(221, 221, 221);
  }

  .table-user-information > tbody > tr:first-child {
      border-top: 0;
  }


  .table-user-information > tbody > tr > td {
      border-top: 0;
  }
  .toppad {
    margin-top:20px;
  }

</style>

  $(document).ready(function() {
      var panels = $('.user-infos');
      var panelsButton = $('.dropdown-user');
      panels.hide();

      //Click dropdown
      panelsButton.click(function() {
          //get data-for attribute
          var dataFor = $(this).attr('data-for');
          var idFor = $(dataFor);

          //current button
          var currentButton = $(this);
          idFor.slideToggle(400, function() {
              //Completed slidetoggle
              if(idFor.is(':visible'))
              {
                  currentButton.html('<i class="glyphicon glyphicon-chevron-up text-muted"></i>');
              }
              else
              {
                  currentButton.html('<i class="glyphicon glyphicon-chevron-down text-muted"></i>');
              }
          })
      });


      $('[data-toggle="tooltip"]').tooltip();

      $('button').click(function(e) {
          e.preventDefault();
          alert("This is a demo.\n :-)");
      });
  });

</script>